### ISSUE TITLE
BUG: dump() fails when path contains a bracket '('

### ISSUE THREAD

**Issue by allardvanhelbergen** [julianburr/sketchtool-cli#1]
Hello, I came across the following. 

**Description:** 
The dump function fails and crashes the script when the path passed to it contains a '(' character. 
```
//script.js
const filePath = '/My/Path/To/A/Sketchfile (with brackets).sketch'
let dump = sketchtool.dump(filePath);
```

**Current behaviour:**
Throws an error
```
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool dump /My/Path/To/A/Sketchfile\ (with\ brackets).sketch'
```
Running ```/Applications/Sketch.app/Contents/Resources/sketchtool/bin/sketchtool dump /My/Path/To/A/Sketchfile\ (with\ brackets).sketch``` directly in terminal does not result in an error. 

**Expected behaviour:**
To execute the command without throwing 

**Proposed solution:**
I don't understand why it throws the error, but perhaps improving the escape function to wrap filenames in double quotes instead of escaping spaces would be better? 

**Current workaround:**
- change the filename so it doesn't have brackets... 😁 
- take care escaping by using ```let dump = JSON.parse(sketchtool.run(`dump "${filePath}"`));``` instead .

**Comment by julianburr** [comment]
Thanks for taking the time to report the issue in such detail :blush::+1: 

Should be fixed in v0.0.3, let me know if it isn't 😅
